### ISSUE TITLE
Should Halftitle be included in Landmarks?

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/selma-lagerlof_the-story-of-gosta-berling_pauline-bancroft-flach#1]
I'm not sure if that is the standard, but I've always included it there in my own productions.

**Comment by robinwhittleton** [comment]
I never have, and I checked a few of @acabal’s productions and it doesn’t seem to be in there either. But I’m willing to be corrected :)

**Comment by drgrigg** [comment]
Fair enough. I thought at one stage lint might have prompted me to do that, but I could easily be wrong -- hence the question mark in the issue title!
