### ISSUE TITLE
Language tags for 'la cachucha'

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/selma-lagerlof_the-story-of-gosta-berling_pauline-bancroft-flach#2]
In chapter-2-5 you've tagged the references to 'la cachuca' with `epub:type="se:name.music"` but I think you should add `xml:lang="es"` to each tag as well.

**Comment by drgrigg** [comment]
To explain my thinking here: in the original page scans the word 'cachuca' isn't capitalised as the **name** of a song would be, but more used as a generic term for a type of dance, like 'tango'. But it's an unusual foreign word which we would expect to see italicised in English text. So I think it's sensible to have both the epub:type and and the xml:lang tag.

**Comment by robinwhittleton** [comment]
I ummed and ahhed about this as cachucha is in MW, but I think it‘s an uncommon enough word to go with your suggestion. Fixed in https://github.com/robinwhittleton/selma-lagerlof_the-story-of-gosta-berling_pauline-bancroft-flach/commit/50a2f68dc16526f39b039aff143f68dbc78ec715.
