### ISSUE TITLE
Page scan source should be included in content.opf

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/selma-lagerlof_the-story-of-gosta-berling_pauline-bancroft-flach#3]
Should be a <dc:source> entry for https://archive.org/details/storygstaberlin02lagegoog

**Comment by robinwhittleton** [comment]
Thanks, fixed in https://github.com/robinwhittleton/selma-lagerlof_the-story-of-gosta-berling_pauline-bancroft-flach/commit/962cc0f7c5cc6e6713cb2c38083a3e257f377f44.
