### ISSUE TITLE
Should dc:description include the protagonist's name?

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/selma-lagerlof_the-story-of-gosta-berling_pauline-bancroft-flach#4]
I thought these short descriptions were meant to be very generic, rather than including a specific character name, eg "A disgraced priest ends up..."

@acabal, what's the standard here?

**Comment by acabal** [comment]
Generally I lean towards more generic, because in a one-sentence summary proper names aren't going to make sense or be useful to the reader. As you noted in your example we can pack more information in by replacing proper names with a generic descriptor.

**Comment by robinwhittleton** [comment]
Thanks, fixed in https://github.com/robinwhittleton/selma-lagerlof_the-story-of-gosta-berling_pauline-bancroft-flach/commit/962cc0f7c5cc6e6713cb2c38083a3e257f377f44.
